export default {
  LOAD_PLANTS: 'LOAD_PLANTS',
  LOAD_USERS: 'USERS_LOAD',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_REGISTER_ERROR: 'AUTH_REGISTER_ERROR',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  LOAD_FAVORITES: 'LOAD_FAVORITES',
  SAVE_FAVORITE: 'SAVE_FAVORITE',
  DELETE_FAVORITE: 'DELETE_FAVORITE',
};
